import { type AppType } from "next/app";
import { ClerkProvider } from "@clerk/nextjs";
import { api } from "~/utils/api";
import Head from "next/head";
import "~/styles/globals.css";
import { Toaster } from "react-hot-toast"
const MyApp: AppType = ({ Component, pageProps }) => {
  return (<ClerkProvider {...pageProps}>
     <Head>
        <title>T3 Twiter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Toaster
          position="bottom-center"
          reverseOrder={false}
        />
    <Component {...pageProps} />
  </ClerkProvider>
  );
};

export default api.withTRPC(MyApp);
