name: CI

on: [push, pull_request]

env:
    DATABASE_URL: "https://fake.com"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # You can adjust the version to whatever you prefer

    - name: Install dependencies
      run: npm install

    - name: TypeScript type check
      run: npx tsc --noEmit

    - name: Run lint
      run: npm run lint # Assumes you have a lint script defined in your package.json

